# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: cimg/base:stable
        user: root
        environment:
            DISPLAY: :99
    steps:
      - checkout
      - run: sudo apt-get update -qq && sudo apt-get install -y -qq xvfb
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: Installing GCC
          command: 'sudo add-apt-repository ppa:ubuntu-toolchain-r/test && apt-get update && apt-get install gcc-10 g++-10 && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Ninja
          command: 'apt-get update && sudo apt-get install ninja-build'
      - run:
          name: Install necessary system packages
          command: 'apt-get update && sudo apt-get install -y libselinux-dev libgl1-mesa-dev pkg-config xorg-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev xkb-data libx11-xcb-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev build-essential libgtk2.0-dev'
      - run:
          name: Install Conan
          command: 'apt-get update && sudo apt-get install -y python3-pip && pip3 install conan'
      - run:
          name: Install conan packages
          command: 'mkdir build && cd build && conan install .. --build=missing -o ruff:build_tests=True'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -GNinja -DBUILD_TESTERS=ON'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          command: Xvfb -ac :99 -screen 0 800x600x16 +extension RANDR
          background: true
      - run:
          name: Ruff Testing
          command: './bin/ruff_test -r=junit'
      - codecov/upload:
          file: 'build/out.xml'
          token: 61b967e0-2c32-474d-862c-27282a72365a

