# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Ninja
          command: 'apt-get update && sudo apt-get install ninja-build'
      - run:
          name: Install necessary system packages
          command: 'apt-get update && sudo apt-get install -y libselinux-dev'
      - run:
          name: Install Conan
          command: 'apt-get update && sudo apt-get install -y python-pip && pip install conan'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild -GNinja'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Ruff Testing
          command: './bin/ruff_test'

