pipeline 
{
	agent any
	stages 
	{
		stage("Configure Artifactory/Conan")
		{
			server = Artifactory.server conan
			client = Artifactory.newConanClient()
			serverName = client.remote.add server: server, repo: conan-local
		}
		stage("Get dependencies and publish build info")
		{
			sh "mkdir -p build"
			dir ('build') 
			{
				def b = client.run(command: "install ..")
				server.publishBuildInfo b
			}
		}
		stage('Build') 
		{
			steps 
			{
				echo 'Building...'
				echo "Running ${env.BUILD_ID} ${env.BUILD_DISPLAY_NAME} on ${env.NODE_NAME} and JOB ${env.JOB_NAME}"
				dir('build')
				{
					sh "cmake ../ -GNinja && ninja"
				}
			}
		}
		stage('Test') 
		{
			steps 
			{
				echo 'Testing...'
				dir('bin')
				{
					sh "./Ruff_test"
				}
			}
		}
		stage('Deploy') 
		{
			steps 
			{
				echo 'Deploying...'
			}
		}
	}
}
